/// Flutter icons Cartoonify
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Cartoonify
///      fonts:
///       - asset: fonts/Cartoonify.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Cartoonify {
  Cartoonify._();

  static const _kFontFam = 'Cartoonify';
  static const String _kFontPkg = null;

  static const IconData photo_camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
